# Simple workflow for deploying a Vite app to GitHub Pages
name: Deploy Vite app to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Single deploy job with environment setup
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 16  # Recommend Node 16+ for Vite compatibility
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Create .env file (optional)
        env:
          # Replace with your actual secret name
          VITE_OMDB_API_KEY: ${{ secrets.VITE_OMDB_API_KEY }}  
        run: |
          echo "VITE_OMDB_API_KEY=${VITE_OMDB_API_KEY}" >> .env
      - name: Build
        run: npm run build
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload your build folder (check your Vite config)
          path: './dist'  # Update if your build output is in a different folder
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
